let currentDate=new Date(),selectedStatuses={},currentLang=localStorage.getItem('att_lang')||CONFIG.DEFAULT_LANG;
document.addEventListener('DOMContentLoaded',()=>{currentDate=new Date();setLang(currentLang);renderDate();renderWorkerList();});
function setLang(lang){currentLang=lang;localStorage.setItem('att_lang',lang);const T=lang==='lo'?CONFIG.LO:CONFIG.ZH;document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.getElementById('page-title').textContent=T.TITLE;document.getElementById('page-sub').textContent=T.SUBTITLE;document.getElementById('s-full-label').textContent=T.FULL;document.getElementById('s-half-label').textContent=T.HALF;document.getElementById('s-absent-label').textContent=T.ABSENT;document.getElementById('save-label').textContent=T.SAVE;document.getElementById('admin-link-text').textContent=T.ADMIN;renderWorkerList();}
function formatDate(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function renderDate(){document.getElementById('current-date').textContent=currentDate.toLocaleDateString(currentLang==='lo'?'lo-LA':'zh-CN',{year:'numeric',month:'long',day:'numeric'});document.getElementById('current-day').textContent=currentDate.toLocaleDateString(currentLang==='lo'?'lo-LA':'zh-CN',{weekday:'long'});}
function changeDate(delta){currentDate.setDate(currentDate.getDate()+delta);renderDate();loadSaved();updateSummary();}
function renderWorkerList(){const T=currentLang==='lo'?CONFIG.LO:CONFIG.ZH;const c=document.getElementById('worker-list');c.innerHTML='';CONFIG.EMPLOYEES.forEach(emp=>{const card=document.createElement('div');card.className='worker-card';card.innerHTML='<div class="worker-name">'+emp.name+'<span class="worker-zh">'+emp.nameZh+'</span></div><div class="status-btns"><button class="status-btn full" onclick="selectStatus('+emp.id+',\'full\',this)"><span class="s-icon">✅</span><span>'+T.FULL+'</span></button><button class="status-btn half" onclick="selectStatus('+emp.id+',\'half\',this)"><span class="s-icon">⚠️</span><span>'+T.HALF+'</span></button><button class="status-btn absent" onclick="selectStatus('+emp.id+',\'absent\',this)"><span class="s-icon">❌</span><span>'+T.ABSENT+'</span></button></div>';c.appendChild(card);});loadSaved();updateSummary();}
function selectStatus(id,status,btn){selectedStatuses[id]=status;const card=btn.closest('.status-btns');card.querySelectorAll('.status-btn').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');updateSummary();}
function updateSummary(){let full=0,half=0,absent=0;Object.values(selectedStatuses).forEach(s=>{if(s==='full')full++;else if(s==='half')half++;else if(s==='absent')absent++;});document.getElementById('s-full').textContent=full;document.getElementById('s-half').textContent=half;document.getElementById('s-absent').textContent=absent;}
function loadSaved(){const dk=formatDate(currentDate);try{const raw=localStorage.getItem('att_data');const all=raw?JSON.parse(raw):[];selectedStatuses={};all.forEach(x=>{if(x.date===dk&&x.worker_id&&x.status)selectedStatuses[x.worker_id]=x.status;});}catch(e){selectedStatuses={};}document.querySelectorAll('.worker-card').forEach((card,i)=>{const empId=CONFIG.EMPLOYEES[i].id;const st=selectedStatuses[empId];card.querySelectorAll('.status-btn').forEach(b=>b.classList.remove('selected'));if(st)card.querySelector('.status-btn.'+st).classList.add('selected');});updateSummary();}
function saveRecord(){const dk=formatDate(currentDate);if(Object.keys(selectedStatuses).length===0){alert(currentLang==='lo'?'ກະລຸນາເລືອກສະຖານະກ່ອນບັນທຶກ':'请先选择考勤状态');return;}const T=currentLang==='lo'?CONFIG.LO:CONFIG.ZH;const btn=document.getElementById('save-btn');btn.textContent='...';btn.disabled=true;try{let records=[];try{records=JSON.parse(localStorage.getItem('att_data'))||[];}catch(e){records=[];}records=records.filter(x=>x.date!==dk);CONFIG.EMPLOYEES.forEach(emp=>{records.push({date:dk,worker_id:emp.id,name:emp.name,name_zh:emp.nameZh,status:selectedStatuses[emp.id]||'absent',saved_at:new Date().toISOString()});});localStorage.setItem('att_data',JSON.stringify(records));btn.textContent=T.SAVED;btn.classList.add('saved');}catch(e){btn.textContent=T.SAVE;alert('保存失败');}btn.disabled=false;setTimeout(()=>{btn.textContent=T.SAVE;btn.classList.remove('saved');},2000);}