let currentDate=new Date(),selectedStatuses={},currentLang=localStorage.getItem('att_lang')||CONFIG.DEFAULT_LANG;
let syncToken=localStorage.getItem('att_token')||'';
let syncData=[];

async function gistRead(){
    if(!syncToken||!CONFIG.GIST_ID){syncData=localStorage.getItem('att_data')?JSON.parse(localStorage.getItem('att_data')):[];return;}
    try{const r=await fetch('https://api.github.com/gists/'+CONFIG.GIST_ID,{headers:{'Authorization':'token '+syncToken,'Accept':'application/vnd.github.v3+json'},signal:AbortSignal.timeout(8000)});const d=await r.json();if(d.message==='Bad credentials'){syncToken='';localStorage.removeItem('att_token');syncData=localStorage.getItem('att_data')?JSON.parse(localStorage.getItem('att_data')):[];return;}const content=d.files[CONFIG.GIST_FILE];if(content){syncData=JSON.parse(content.content);}else{syncData=[];}}catch(e){syncData=localStorage.getItem('att_data')?JSON.parse(localStorage.getItem('att_data')):[];}
}

async function gistWrite(){
    localStorage.setItem('att_data',JSON.stringify(syncData));
    if(!syncToken||!CONFIG.GIST_ID)return;
    try{await fetch('https://api.github.com/gists/'+CONFIG.GIST_ID,{method:'PATCH',headers:{'Authorization':'token '+syncToken,'Content-Type':'application/json','Accept':'application/vnd.github.v3+json'},body:JSON.stringify({files:{[CONFIG.GIST_FILE]:{content:JSON.stringify(syncData)}}}),signal:AbortSignal.timeout(8000)});}catch(e){}
}

document.addEventListener('DOMContentLoaded',()=>{currentDate=new Date();setLang(currentLang);renderDate();renderWorkerList();});
function setLang(lang){currentLang=lang;localStorage.setItem('att_lang',lang);const T=lang==='lo'?CONFIG.LO:CONFIG.ZH;document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.getElementById('page-title').textContent=T.TITLE;document.getElementById('page-sub').textContent=T.SUBTITLE;document.getElementById('s-full-label').textContent=T.FULL;document.getElementById('s-half-label').textContent=T.HALF;document.getElementById('s-absent-label').textContent=T.ABSENT;document.getElementById('save-label').textContent=T.SAVE;document.getElementById('admin-link-text').textContent=T.ADMIN;renderWorkerList();}
function formatDate(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function renderDate(){document.getElementById('current-date').textContent=currentDate.toLocaleDateString(currentLang==='lo'?'lo-LA':'zh-CN',{year:'numeric',month:'long',day:'numeric'});document.getElementById('current-day').textContent=currentDate.toLocaleDateString(currentLang==='lo'?'lo-LA':'zh-CN',{weekday:'long'});}
function changeDate(delta){currentDate.setDate(currentDate.getDate()+delta);renderDate();loadSaved();updateSummary();}
function renderWorkerList(){const T=currentLang==='lo'?CONFIG.LO:CONFIG.ZH;const c=document.getElementById('worker-list');c.innerHTML='';CONFIG.EMPLOYEES.forEach(emp=>{const card=document.createElement('div');card.className='worker-card';card.innerHTML='<div class="worker-name">'+emp.name+'<span class="worker-zh">'+emp.nameZh+'</span></div><div class="status-btns"><button class="status-btn full" onclick="selectStatus('+emp.id+',\'full\',this)"><span class="s-icon">✅</span><span>'+T.FULL+'</span></button><button class="status-btn half" onclick="selectStatus('+emp.id+',\'half\',this)"><span class="s-icon">⚠️</span><span>'+T.HALF+'</span></button><button class="status-btn absent" onclick="selectStatus('+emp.id+',\'absent\',this)"><span class="s-icon">❌</span><span>'+T.ABSENT+'</span></button></div>';c.appendChild(card);});loadSaved();updateSummary();}
function selectStatus(id,status,btn){selectedStatuses[id]=status;const card=btn.closest('.status-btns');card.querySelectorAll('.status-btn').forEach(b=>b.classList.remove('selected'));btn.classList.add('selected');updateSummary();}
function updateSummary(){let full=0,half=0,absent=0;Object.values(selectedStatuses).forEach(s=>{if(s==='full')full++;else if(s==='half')half++;else if(s==='absent')absent++;});document.getElementById('s-full').textContent=full;document.getElementById('s-half').textContent=half;document.getElementById('s-absent').textContent=absent;}
async function loadSaved(){const dk=formatDate(currentDate);await gistRead();selectedStatuses={};syncData.forEach(x=>{if(x.date===dk&&x.worker_id&&x.status)selectedStatuses[x.worker_id]=x.status;});document.querySelectorAll('.worker-card').forEach((card,i)=>{const empId=CONFIG.EMPLOYEES[i].id;const st=selectedStatuses[empId];card.querySelectorAll('.status-btn').forEach(b=>b.classList.remove('selected'));if(st)card.querySelector('.status-btn.'+st).classList.add('selected');});updateSummary();}
async function saveRecord(){const dk=formatDate(currentDate);if(Object.keys(selectedStatuses).length===0){alert(currentLang==='lo'?'ກະລຸນາເລືອກສະຖານະກ່ອນບັນທຶກ':'请先选择考勤状态');return;}const T=currentLang==='lo'?CONFIG.LO:CONFIG.ZH;const btn=document.getElementById('save-btn');btn.textContent='...';btn.disabled=true;await gistRead();syncData=syncData.filter(x=>x.date!==dk);CONFIG.EMPLOYEES.forEach(emp=>{syncData.push({date:dk,worker_id:emp.id,name:emp.name,name_zh:emp.nameZh,status:selectedStatuses[emp.id]||'absent',saved_at:new Date().toISOString()});});await gistWrite();btn.textContent=T.SAVED;btn.classList.add('saved');btn.disabled=false;setTimeout(()=>{btn.textContent=T.SAVE;btn.classList.remove('saved');},2000);}
function showTokenModal(){const T=currentLang==='lo'?CONFIG.LO:CONFIG.ZH;const overlay=document.createElement('div');overlay.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.5);z-index:100;display:flex;align-items:center;justify-content:center;';const box=document.createElement('div');box.style.cssText='background:white;border-radius:16px;padding:24px;width:90%;max-width:360px;text-align:center;';box.innerHTML='<h3 style="margin:0 0 8px">'+T.SET_TOKEN+'</h3><p style="color:#888;font-size:13px;margin:0 0 16px">GitHub Personal Access Token</p><input id="token-input" type="text" placeholder="ghp_..." style="width:100%;padding:12px;border:1px solid #ddd;border-radius:8px;font-size:14px;box-sizing:border-box" value="'+syncToken+'"><p id="token-msg" style="color:#888;font-size:12px;margin:8px 0 0;min-height:18px"></p><div style="display:flex;gap:10px;margin-top:16px"><button id="token-cancel" style="flex:1;padding:10px;border:1px solid #ddd;border-radius:8px;background:white;cursor:pointer">✕</button><button id="token-save" style="flex:1;padding:10px;border:none;border-radius:8px;background:#28a745;color:white;cursor:pointer">OK</button></div>';overlay.appendChild(box);document.body.appendChild(overlay);const inp=document.getElementById('token-input');const msg=document.getElementById('token-msg');document.getElementById('token-cancel').onclick=()=>overlay.remove();document.getElementById('token-save').onclick=async()=>{const v=inp.value.trim();if(!v){inp.style.borderColor='red';msg.textContent=currentLang==='lo'?'ກະລຸນາໃສ່ Token':'请输入Token';msg.style.color='red';return;}setToken(v);msg.textContent='⏳ '+(currentLang==='lo'?'ກຳລັງກວດສອບ...':'验证中...');msg.style.color='#666';try{const r=await fetch('https://api.github.com/gists/'+CONFIG.GIST_ID,{headers:{'Authorization':'token '+v,'Accept':'application/vnd.github.v3+json'},signal:AbortSignal.timeout(10000)});const d=await r.json();if(d.id){msg.textContent='✅ '+(currentLang==='lo'?'Token ຖືກຕ້ອງ!':'Token 有效!');msg.style.color='#22c55e';setTimeout(()=>overlay.remove(),1000);}else if(d.message==='Bad credentials'){setToken('');msg.textContent='❌ '+(currentLang==='lo'?'Token ບໍ່ຖືກ':'Token 无效');msg.style.color='red';}else{msg.textContent='✅ '+(currentLang==='lo'?'Token ຖືກຕ້ອງ!':'Token 有效!');msg.style.color='#22c55e';setTimeout(()=>overlay.remove(),1000);}}catch(e){msg.textContent='✅ '+(currentLang==='lo'?'Token ບັນທຶກແລ້ວ ແຕ່ລະບົບບໍ່ສາມາດເຊື່ອມຕໍ່':'Token 已保存，暂时无法联网验证');msg.style.color='#f59e0b';setTimeout(()=>overlay.remove(),2000);}};}
